name = "MinGal"
uuid = "def1ee67-34f5-4655-97c4-ec0ddae1637c"
authors = ["Vitor <vitorlorencone@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
