name = "MinGal"
uuid = "ac8882cc-b2bf-4c44-88a5-a54ff16a06a3"
authors = ["Vitor <vitorlorencone@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
